title: Safe Segmentation Competition-ICPR-24
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
theme: jekyll-theme-cayman
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
