lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
theme: jekyll-theme-minimal
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
